name: Update Docker Image

# the project is already auto deployed with heroku so I just want to auto update the docker image when branch updated

# Trigger deployment only on push to master branch
on:
  push:
    branches:
      - main

jobs:
  build-docker:
    name: "Build Docker Container"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup GO
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'
      
      - name: login to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }} 
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/alterra-day-10:latest